method: RhoLoss
method_opt:
  ratio: 0.1
  balance: False
  ratio_scheduler: constant
  warmup_epochs: 0
  uniform_epochs: 1

teacher_model_path: None
teacher_architecture: smallcnn.yaml
teacher_optimizer: /home/lgreen/projects/Online_BS/configs/optim/sgdn-30-0.0025-0.0.yaml
