training_opt:
  num_epochs: 30
  num_data_workers: 4
  batch_size: 320
  test_batch_size: 512
  optimizer: AdamW
  optim_params:
    lr: 0.001
    weight_decay: 0.01
    betas: [0.9, 0.999]
    eps: 1.0e-08
  scheduler_params: {}
  scheduler: 'constant'

  loss_type: CrossEntropy
  loss_params: {}