training_opt:
  num_epochs: 30
  # num_steps: 100000
  num_data_workers: 0
  batch_size: 32
  optimizer: SGD
  opt_args:
    lr: 0.0025
    momentum: 0.9
    nesterov: true
    weight_decay: 0.0
  sched_args: null
  scheduler: cosine